spring:
  application:
    name: hipreader

  data:
    redis:
      host: ${spring.data.redis.host:localhost}
      port: ${spring.data.redis.port:6379}
      lettuce:
        pool:
          max-idle: 5
          min-idle: 2
          max-active: 5

  datasource:
    url: ${DB_URL}?rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    key: ${jwt.secret.key}
